export = [
  { initials: 'AC', name: 'Acre', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'AL', name: 'Alagoas', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'AP', name: 'Amapá', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'AM', name: 'Amazonas', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'BA', name: 'Bahia', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'CE', name: 'Ceará', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'DF', name: 'Distrito Federal', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'ES', name: 'Espírito Santo', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'GO', name: 'Goiás', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'MA', name: 'Maranhão', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'MT', name: 'Mato Grosso', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'MS', name: 'Mato Grosso do Sul', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'MG', name: 'Minas Gerais', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'PA', name: 'Pará', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'PB', name: 'Paraíba', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'PR', name: 'Paraná', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'PE', name: 'Pernambuco', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'PI', name: 'Piauí', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'RJ', name: 'Rio de Janeiro', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'RN', name: 'Rio Grande do Norte', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'RS', name: 'Rio Grande do Sul', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'RO', name: 'Rondônia', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'RR', name: 'Roraima', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'SC', name: 'Santa Catarina', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'SP', name: 'São Paulo', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'SE', name: 'Sergipe', createdAt: new Date(), updatedAt: new Date() },
  { initials: 'TO', name: 'Tocantins', createdAt: new Date(), updatedAt: new Date() }
];
